version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\nodejs-express-on-aws-ec2
hooks:
  ApplicationStop:
    - location: \scripts\application_stop.bat
      timeout: 300
  BeforeInstall:
    - location: \scripts\before_install.bat
      timeout: 300
  ApplicationStart:
    - location: \scripts\application_start.bat
      timeout: 300
