version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\nodejs-express-on-aws-ec2
    overwrite: true
hooks:
  ApplicationStop:
    - location: \scripts\application_stop.bat
      timeout: 300
      runas: Administrator
  BeforeInstall:
    - location: \scripts\before_install.bat
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: \scripts\application_start.bat
      timeout: 300
      runas: Administrator
